/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Point;
import java.awt.Color;

import java.awt.Graphics2D;
import java.util.HashSet;

/**
 *
 * @author Roland
 */
public class DrawingPanel extends javax.swing.JPanel {
    
    HashSet<Point> points;
    Point selected;

    /**
     * Creates new form DrawingPanel
     */
    public DrawingPanel() {
        initComponents();
        
    }
    
    public boolean setPoints(HashSet<Point> p) {
        if(p == null) {
            return false;
        }
        points = p;
        return true;
    }
    
    
    public void paintPoints() {
        Graphics2D g = (Graphics2D) this.getGraphics();
        super.paintComponent(g);
        for(Point p: points) {
            int x = (int) p.getX();
            int y = (int) p.getY();
            
            g.drawOval(20+x, 10+y, 5, 5);
            g.fillOval(20+x, 10+y, 5, 5);
            g.drawString(p.getName() + "("+(x)+","+ y + ")", x, 30+y);
        }
    }
    
    public void selectPoint(Point p) {
        selected = p;
        Graphics2D g = (Graphics2D) this.getGraphics();
        super.paintComponent(g);
        int x = (int) p.getX();
        int y = (int) p.getY();
        g.setColor(Color.RED);
        g.drawOval(20+x, 10+y, 5, 5);
        g.fillOval(20+x, 10+y, 5, 5);
        g.drawString(p.getName() + "("+(x)+","+ y + ")", x, 30+y);
    }
    
    public void unselectPoints() {
        if(selected != null) {
            Graphics2D g = (Graphics2D) this.getGraphics();
            super.paintComponent(g);
            int x = (int) selected.getX();
            int y = (int) selected.getY();
            g.setColor(Color.BLACK);
            g.drawOval(20+x, 10+y, 5, 5);
            g.fillOval(20+x, 10+y, 5, 5);
            g.drawString(selected.getName() + "("+(x)+","+ y + ")", x, 30+y);
            selected=null;
        }
        else {
            
        }
    }
    
    public void removePoint(Point p) {
        Graphics2D g = (Graphics2D) this.getGraphics();
        super.paintComponent(g);
        int x = (int) p.getX();
        int y = (int) p.getY();
        
        g.setColor(getBackground());
        g.drawOval(20+x, 10+y, 5, 5);
        g.fillOval(20+x, 10+y, 5, 5);
        g.drawString(p.getName() + "("+(x)+","+ y + ")", x, 30+y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
